print("Ecuacion pendiente")
print()
x1 = float(input("Ingrese x1: "))
x2 = float(input("Ingrese x2: "))
y1 = float(input("Ingrese y1: "))
y2 = float(input("Ingrese y2: "))
m = (y2 - y1) / (x2 - x1)
print("La pendiente es: ", m)